convert ./cifar10/qual_pluralistic/patches_0.png ./cifar10/qual_pluralistic/patches_0.jpg
convert ./cifar10/qual_pluralistic/patches_17.png ./cifar10/qual_pluralistic/patches_17.jpg
convert ./cifar10/qual_pluralistic/patches_33.png ./cifar10/qual_pluralistic/patches_33.jpg
convert ./cifar10/qual_pluralistic/patches_10.png ./cifar10/qual_pluralistic/patches_10.jpg
convert ./cifar10/qual_pluralistic/patches_1.png ./cifar10/qual_pluralistic/patches_1.jpg
convert ./cifar10/qual_ce/patches_0.png ./cifar10/qual_ce/patches_0.jpg
convert ./cifar10/qual_ce/patches_17.png ./cifar10/qual_ce/patches_17.jpg
convert ./cifar10/qual_ce/patches_33.png ./cifar10/qual_ce/patches_33.jpg
convert ./cifar10/qual_ce/patches_10.png ./cifar10/qual_ce/patches_10.jpg
convert ./cifar10/qual_ce/patches_1.png ./cifar10/qual_ce/patches_1.jpg
convert ./cifar10/qual_vae-reverse/patches_0.png ./cifar10/qual_vae-reverse/patches_0.jpg
convert ./cifar10/qual_vae-reverse/patches_17.png ./cifar10/qual_vae-reverse/patches_17.jpg
convert ./cifar10/qual_vae-reverse/patches_33.png ./cifar10/qual_vae-reverse/patches_33.jpg
convert ./cifar10/qual_vae-reverse/patches_10.png ./cifar10/qual_vae-reverse/patches_10.jpg
convert ./cifar10/qual_vae-reverse/patches_1.png ./cifar10/qual_vae-reverse/patches_1.jpg
convert ./cifar10/qual_vae-forward/patches_0.png ./cifar10/qual_vae-forward/patches_0.jpg
convert ./cifar10/qual_vae-forward/patches_17.png ./cifar10/qual_vae-forward/patches_17.jpg
convert ./cifar10/qual_vae-forward/patches_33.png ./cifar10/qual_vae-forward/patches_33.jpg
convert ./cifar10/qual_vae-forward/patches_10.png ./cifar10/qual_vae-forward/patches_10.jpg
convert ./cifar10/qual_vae-forward/patches_1.png ./cifar10/qual_vae-forward/patches_1.jpg
convert ./cifar10/qual_np/patches_0.png ./cifar10/qual_np/patches_0.jpg
convert ./cifar10/qual_np/patches_17.png ./cifar10/qual_np/patches_17.jpg
convert ./cifar10/qual_np/patches_33.png ./cifar10/qual_np/patches_33.jpg
convert ./cifar10/qual_np/patches_10.png ./cifar10/qual_np/patches_10.jpg
convert ./cifar10/qual_np/patches_1.png ./cifar10/qual_np/patches_1.jpg
convert ./ffhq256/qual_pluralistic/patches_0.png ./ffhq256/qual_pluralistic/patches_0.jpg
convert ./ffhq256/qual_pluralistic/patches_13.png ./ffhq256/qual_pluralistic/patches_13.jpg
convert ./ffhq256/qual_pluralistic/patches_43.png ./ffhq256/qual_pluralistic/patches_43.jpg
convert ./ffhq256/qual_pluralistic/patches_32.png ./ffhq256/qual_pluralistic/patches_32.jpg
convert ./ffhq256/qual_pluralistic/patches_44.png ./ffhq256/qual_pluralistic/patches_44.jpg
convert ./ffhq256/qual_ce/patches_0.png ./ffhq256/qual_ce/patches_0.jpg
convert ./ffhq256/qual_ce/patches_13.png ./ffhq256/qual_ce/patches_13.jpg
convert ./ffhq256/qual_ce/patches_43.png ./ffhq256/qual_ce/patches_43.jpg
convert ./ffhq256/qual_ce/patches_32.png ./ffhq256/qual_ce/patches_32.jpg
convert ./ffhq256/qual_ce/patches_44.png ./ffhq256/qual_ce/patches_44.jpg
convert ./ffhq256/qual_vae-reverse/patches_0.png ./ffhq256/qual_vae-reverse/patches_0.jpg
convert ./ffhq256/qual_vae-reverse/patches_13.png ./ffhq256/qual_vae-reverse/patches_13.jpg
convert ./ffhq256/qual_vae-reverse/patches_43.png ./ffhq256/qual_vae-reverse/patches_43.jpg
convert ./ffhq256/qual_vae-reverse/patches_32.png ./ffhq256/qual_vae-reverse/patches_32.jpg
convert ./ffhq256/qual_vae-reverse/patches_44.png ./ffhq256/qual_vae-reverse/patches_44.jpg
convert ./ffhq256/qual_vae-forward/patches_0.png ./ffhq256/qual_vae-forward/patches_0.jpg
convert ./ffhq256/qual_vae-forward/patches_13.png ./ffhq256/qual_vae-forward/patches_13.jpg
convert ./ffhq256/qual_vae-forward/patches_43.png ./ffhq256/qual_vae-forward/patches_43.jpg
convert ./ffhq256/qual_vae-forward/patches_32.png ./ffhq256/qual_vae-forward/patches_32.jpg
convert ./ffhq256/qual_vae-forward/patches_44.png ./ffhq256/qual_vae-forward/patches_44.jpg
convert ./ffhq256/qual_np/patches_0.png ./ffhq256/qual_np/patches_0.jpg
convert ./ffhq256/qual_np/patches_13.png ./ffhq256/qual_np/patches_13.jpg
convert ./ffhq256/qual_np/patches_43.png ./ffhq256/qual_np/patches_43.jpg
convert ./ffhq256/qual_np/patches_32.png ./ffhq256/qual_np/patches_32.jpg
convert ./ffhq256/qual_np/patches_44.png ./ffhq256/qual_np/patches_44.jpg
